modLoader="javafml"
loaderVersion="[47,)"
license="${modLicense}"
issueTrackerURL="${modIssueTrackerUrl}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''
${modDescription}
'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion},1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="kotlinforforge"
mandatory=true
versionRange="[${kotlinForForgeVersion},)"
ordering="NONE"
side="BOTH"
